language: python

python:
  - 3.5

addons:
  apt:
    packages:
      - pyqt5-dev-tools

git:
  submodules: false

before_install:
  - >-
    openssl aes-256-cbc
    -K $encrypted_9cff7cfa6b9c_key
    -iv $encrypted_9cff7cfa6b9c_iv
    -in github_deploy_key.enc
    -out github_deploy_key.out
    -d
  - chmod 600 github_deploy_key.out
  - eval $(ssh-agent -s)
  - ssh-add github_deploy_key.out
  - git submodule update --init --recursive

install:
  - pip install -r requirements.txt

script:
  - pyrcc5 -o swiss_locator/resources_rc.py swiss_locator/resources.qrc


jobs:
  include:
    - stage: deploy
      if: tag IS present
      script: plugin_ci/release/release.sh

    - stage: deploy
      if: branch = master AND type != pull_request
      script: plugin_ci/translate/update-translations.sh

env:
  global:
    # OSGEO credentials to release the plugin
    # Generate with the following command for proper special characters support
    # travis encrypt OSGEO_PASSWORD=\''Your super secret password!'\'
    - OSGEO_USERNAME=3nids
    - secure: "FGDDbMkw5FaPKnLd3F01QvRWQ3MXBcwwSVSTFY0LsTi1tjptcoAiCCDguL6+PS+1scTMgHO7QbLN9AVfToRkCliaBJFPI8xnviOOtR3KUAIdD/h7WzzD5sB1IYEJmZ3aexV53dE8VGdC5NDTCM1iujEuJq8SNSmZTmmaiT8yKzUE/Ds0oWJYF5gsqUoKv0YTpJ/wUdMa9jYOs7fiXOFn+5yuvS2bUIm/RCzAYQZseee1HXIgyV04OZzCWAOOfBnKJbfa9XDtu2AoEXIGNn+zjkSaroIAJ+XNTTSbywFnISux2Vc9j5+YYop2att69p904hySQLar+DTExexCtwKWmts9dBQNrnqGo0VfWQT1iyjwufsGbCKpTBT+ZEDHXn1hr9XdLKYMqvVGgPe+jF7YFJxlewBt6byktKyOFLsfLhUKpB+SPpzdyYioFsKs6+iUkOZTshFb3NCvpqgSJh7b3Ej3xTwFh/oCQD4s6HdG4o02i7BCLo2nP2r2XyECxkeOKvLDQBrCPSmeoeLqwLSwNJ+k9mg+AUR8DZy+j0+jV+z5CUPvs8CP/3Al/5ckXucj1C5bmI77KxE+tF0UrYGCY2j4n4SiyYEjqh4ff1rUKlxCTjU1rCRbOkjvGg6Qtu0+FAHpfwUg8gM0qAb6W9svjaNuYVcx2mr/x+xT8chPywc="
    # TRANSIFEX_API_TOKEN, generated on Transifex website
    # travis encrypt TX_TOKEN="......"
    - secure: "mNXtVxVr3nUjpoL/92+QgT69MyefJozpXYPLMrMddwCrfC04gcfYFTh0z2auk5RdM4aFXrf0paSRZQg952196k3SGqX9PBc21YTSDFQp4uvoiEeH2SvqXa2j4mgi21LqMTwk1PYUxYFnkc8xdB3zPFpu8T8jQ42qrPEleF0nCm+FJsSR+sjNwEELkdUkiC3ekFAReMCnlCXfYyP9T5RU3P9lxj8ceLGkJ1eHtt7zsa8EOysUXs88GFlWcvRSH04wm95p7ZY+y5vXq3fE4jzixP+XgK9HxAPcU2Rvpjgk5pcjTDlfnwNDmCONWax1XGvUur19QkTjECcI1DqHkMoW9/l8nluKzL9dufM658605Q4ctSVDqdUSF3EU9G9UQLV0wAiKqwpzg7T3GuELqDKvCuVSF95MrD3c5rmSMOv6T2ZMHF3rSr0GiUOOH+ZSZjWs/IOC541KEB4cPUTVJ+4GLjs+RzZxM1CXU9VVyn2LmSPP9RXjZACRQsZvC3XL6Cxq5CCcl8SE/4amyVw5YjVN0jJFObsYNtgqR9cDPfDmWVNMTssdjZVA15VSEUD7KTB+4mEyArFod92w/FCwzlMp1QuBMXL1NzURUz1JE9a2KKWr+T6bzSNoeyN5/n07yMYf4tPfcApAcZukHyntPeKfrASZcQmsmlcvY/XMRgjCHjU="

    # GH_TOKEN for creating releases
    # https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line
    # authorize only "repo_deployment"
    # travis encrypt GH_TOKEN="......"
    - secure: "LsnPmJYy7GUPhOClE7e7YV/486nJ4c4u465jpgsxG2vY7GZ30aZFVMN2R1Iw3oh6fhzMx9CEd73mqHsL6qd7ozrzwzB4YpRW0PutHp9/pfe7WkkSGO8WLrYimzEr4YMnf/ZXTebgcijXtBRQZDiv28Qkhb0pR3gwnptboC8hz2bI/LVnvVbDehzjwoWCJiO4wnRJCIYWsloJ5WHnNghpmP85+dLxXeeQQk30Ij3Y3Qdm30ncPALrVf0zrO7BiFMW2CxQ1VdmoRuyyDgQvqZJ8Kj1bBRwuLFyLP2LLy52vcBuj3qztG/wHyNxsJG3ypqMn5CN3px1k4kD1zQd9EgNUuOGHoxs6bP64TISjTH3PL9IKiiiQT/Y1HEXzjSk49T8OaHM3tmStipmushSLp5lTRoFrCbrJbZYxQB4nveKU/4HbR5LAz9RFQTxLdaYXEvSCkrgmjqBfeAUhfVCRVQOcKDfBUDH2oIXJD34JUMUgr9Bm1IWbOoZ4bZgNKfpTYErEbpl66ktx+uLgED00QuK5IIJMqW29I9y9s9Q/e61RrCpmAK9oRWIgUMYX2eDx2jySZ3SaLPZjb5cCY8DHpuwTIy8ENB0V80dxjnfkua4TSPCu9D50CpSw555VKGWccSKDz8+vDydA8Y10vDOa8TpuMm+3MHCdmisnGqS6H+xQ4U="